development:
  adapter: mysql2
  database: rss_watching
  username: root
  password: root

test:
  adapter: mysql2
  database: rss_watching
  username: root
  password: root

production:
  adapter: mysql2
  database: rss_watching
  username: root
  password: chilibpi
  encoding: utf8
